model:
  name: tiny
  vocab_size: 8
  context_length: ${data.context_length}
  d_model: 256
  num_heads: 8
  d_ff: 1024
  num_layers: 8
  theta: 10000.0
  checkpointing_blocksize: 1
tokenizer:
  kind: kmer
  kmer_size: 1
  stride: 1
  add_bos: false
  add_eos: true
experiment:
  name: small_tokenizer_comparison
  output_dir: /home/wjiang34/LLM/TriEvo/out_experiments/small_tokenizer_comparison/1_1
  checkpoint_dir: /home/wjiang34/LLM/TriEvo/out_experiments/small_tokenizer_comparison/1_1/checkpoints
  log_dir: /home/wjiang34/LLM/TriEvo/out_experiments/small_tokenizer_comparison/1_1/logs
  tb_log_dir: /home/wjiang34/LLM/TriEvo/out_experiments/small_tokenizer_comparison/1_1/tb_logs
  do_accounting: true
  do_train: true
  do_eval: false
  do_predict: false
data:
  dataset_root: dataset/refseq_viral
  train_path: /home/wjiang34/LLM/TriEvo/dataset/refseq_viral/k1_s1/train_vir.bin
  val_path: /home/wjiang34/LLM/TriEvo/dataset/refseq_viral/k1_s1/val_vir.bin
  test_path: /home/wjiang34/LLM/TriEvo/dataset/refseq_viral/k1_s1/test_vir.bin
  batch_size: 256
  context_length: 4096
training:
  train_num_iterations: 3000
  eval_num_iterations: 300
  max_lr: 0.003
  min_lr: 0.0003
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-08
  weight_decay: 0.01
  max_l2_norm: 5.0
  warm_up_steps: 300
  anneal_steps: 3000
  log_interval: 3
  val_interval: 300
  save_interval: 300
  val_num_iterations: 150
  resume_from: 0
runtime:
  device: cuda
  dtype: float32
  seed: 42
  compile: true
prediction:
  input_fasta_path: null
  output_dir: null
  max_length: ${data.context_length}
  temperature: 1.0
  top_p: 0.9
